// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: test.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*Frame_Echo
	//	*Frame_Ping
	Msg isFrame_Msg `protobuf_oneof:"Msg"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (m *Frame) GetMsg() isFrame_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *Frame) GetEcho() *MsgEcho {
	if x, ok := x.GetMsg().(*Frame_Echo); ok {
		return x.Echo
	}
	return nil
}

func (x *Frame) GetPing() *MsgPing {
	if x, ok := x.GetMsg().(*Frame_Ping); ok {
		return x.Ping
	}
	return nil
}

type isFrame_Msg interface {
	isFrame_Msg()
}

type Frame_Echo struct {
	Echo *MsgEcho `protobuf:"bytes,1,opt,name=Echo,proto3,oneof"`
}

type Frame_Ping struct {
	Ping *MsgPing `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

func (*Frame_Echo) isFrame_Msg() {}

func (*Frame_Ping) isFrame_Msg() {}

type MsgEcho struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *MsgEcho) Reset() {
	*x = MsgEcho{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgEcho) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgEcho) ProtoMessage() {}

func (x *MsgEcho) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgEcho.ProtoReflect.Descriptor instead.
func (*MsgEcho) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *MsgEcho) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type MsgPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgPing) Reset() {
	*x = MsgPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPing) ProtoMessage() {}

func (x *MsgPing) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPing.ProtoReflect.Descriptor instead.
func (*MsgPing) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

var File_test_proto protoreflect.FileDescriptor

var file_test_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65,
	0x73, 0x74, 0x22, 0x58, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x45,
	0x63, 0x68, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x4d, 0x73, 0x67, 0x45, 0x63, 0x68, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x45, 0x63, 0x68, 0x6f,
	0x12, 0x23, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x04, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x05, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x1d, 0x0a, 0x07,
	0x4d, 0x73, 0x67, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x09, 0x0a, 0x07, 0x4d,
	0x73, 0x67, 0x50, 0x69, 0x6e, 0x67, 0x32, 0x84, 0x01, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x12, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x1a, 0x0b, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x27,
	0x0a, 0x07, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x32, 0x12, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x1a, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x24, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12,
	0x0d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x45, 0x63, 0x68, 0x6f, 0x1a, 0x0d,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x45, 0x63, 0x68, 0x6f, 0x42, 0x08, 0x5a,
	0x06, 0x2e, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData = file_test_proto_rawDesc
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_proto_rawDescData)
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test_proto_goTypes = []interface{}{
	(*Frame)(nil),   // 0: test.Frame
	(*MsgEcho)(nil), // 1: test.MsgEcho
	(*MsgPing)(nil), // 2: test.MsgPing
}
var file_test_proto_depIdxs = []int32{
	1, // 0: test.Frame.Echo:type_name -> test.MsgEcho
	2, // 1: test.Frame.ping:type_name -> test.MsgPing
	0, // 2: test.TestService.Stream:input_type -> test.Frame
	0, // 3: test.TestService.Stream2:input_type -> test.Frame
	1, // 4: test.TestService.Echo:input_type -> test.MsgEcho
	0, // 5: test.TestService.Stream:output_type -> test.Frame
	0, // 6: test.TestService.Stream2:output_type -> test.Frame
	1, // 7: test.TestService.Echo:output_type -> test.MsgEcho
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgEcho); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_test_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Frame_Echo)(nil),
		(*Frame_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_rawDesc = nil
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
